/**
 * CrowdLabelAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The HelloResponse model module.
 * @module model/HelloResponse
 * @version 0.1.0
 */
class HelloResponse {
    /**
     * Constructs a new <code>HelloResponse</code>.
     * @alias module:model/HelloResponse
     * @param hello {String} 
     */
    constructor(hello) { 
        
        HelloResponse.initialize(this, hello);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hello) { 
        obj['hello'] = hello;
    }

    /**
     * Constructs a <code>HelloResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HelloResponse} obj Optional instance to populate.
     * @return {module:model/HelloResponse} The populated <code>HelloResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HelloResponse();

            if (data.hasOwnProperty('hello')) {
                obj['hello'] = ApiClient.convertToType(data['hello'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>HelloResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>HelloResponse</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of HelloResponse.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hello'] && !(typeof data['hello'] === 'string' || data['hello'] instanceof String)) {
            throw new Error("Expected the field `hello` to be a primitive type in the JSON string but got " + data['hello']);
        }

        return true;
    }


}

HelloResponse.RequiredProperties = ["hello"];

/**
 * @member {String} hello
 */
HelloResponse.prototype['hello'] = undefined;






export default HelloResponse;

