/**
 * CrowdLabelAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The Registration model module.
 * @module model/Registration
 * @version 0.1.0
 */
class Registration {
    /**
     * Constructs a new <code>Registration</code>.
     * @alias module:model/Registration
     * @param username {String} 
     * @param password {String} 
     * @param email {String} 
     * @param userType {Number} 
     * @param verificationCode {String} 
     */
    constructor(username, password, email, userType, verificationCode) { 
        
        Registration.initialize(this, username, password, email, userType, verificationCode);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, username, password, email, userType, verificationCode) { 
        obj['username'] = username;
        obj['password'] = password;
        obj['email'] = email;
        obj['user_type'] = userType;
        obj['verification_code'] = verificationCode;
    }

    /**
     * Constructs a <code>Registration</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Registration} obj Optional instance to populate.
     * @return {module:model/Registration} The populated <code>Registration</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Registration();

            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('user_type')) {
                obj['user_type'] = ApiClient.convertToType(data['user_type'], 'Number');
            }
            if (data.hasOwnProperty('verification_code')) {
                obj['verification_code'] = ApiClient.convertToType(data['verification_code'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>Registration</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>Registration</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of Registration.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['username'] && !(typeof data['username'] === 'string' || data['username'] instanceof String)) {
            throw new Error("Expected the field `username` to be a primitive type in the JSON string but got " + data['username']);
        }
        // ensure the json data is a string
        if (data['password'] && !(typeof data['password'] === 'string' || data['password'] instanceof String)) {
            throw new Error("Expected the field `password` to be a primitive type in the JSON string but got " + data['password']);
        }
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // ensure the json data is a string
        if (data['verification_code'] && !(typeof data['verification_code'] === 'string' || data['verification_code'] instanceof String)) {
            throw new Error("Expected the field `verification_code` to be a primitive type in the JSON string but got " + data['verification_code']);
        }

        return true;
    }


}

Registration.RequiredProperties = ["username", "password", "email", "user_type", "verification_code"];

/**
 * @member {String} username
 */
Registration.prototype['username'] = undefined;

/**
 * @member {String} password
 */
Registration.prototype['password'] = undefined;

/**
 * @member {String} email
 */
Registration.prototype['email'] = undefined;

/**
 * @member {Number} user_type
 */
Registration.prototype['user_type'] = undefined;

/**
 * @member {String} verification_code
 */
Registration.prototype['verification_code'] = undefined;






export default Registration;

