/**
 * CrowdLabelAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Availability from './model/Availability';
import Credentials from './model/Credentials';
import HTTPValidationError from './model/HTTPValidationError';
import HelloRequest from './model/HelloRequest';
import HelloResponse from './model/HelloResponse';
import JWT from './model/JWT';
import LocationInner from './model/LocationInner';
import Registration from './model/Registration';
import ValidationError from './model/ValidationError';
import DefaultApi from './api/DefaultApi';


/**
* JS API client generated by OpenAPI Generator.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var CrowdLabelApi = require('index'); // See note below*.
* var xxxSvc = new CrowdLabelApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new CrowdLabelApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new CrowdLabelApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new CrowdLabelApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 0.1.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Availability model constructor.
     * @property {module:model/Availability}
     */
    Availability,

    /**
     * The Credentials model constructor.
     * @property {module:model/Credentials}
     */
    Credentials,

    /**
     * The HTTPValidationError model constructor.
     * @property {module:model/HTTPValidationError}
     */
    HTTPValidationError,

    /**
     * The HelloRequest model constructor.
     * @property {module:model/HelloRequest}
     */
    HelloRequest,

    /**
     * The HelloResponse model constructor.
     * @property {module:model/HelloResponse}
     */
    HelloResponse,

    /**
     * The JWT model constructor.
     * @property {module:model/JWT}
     */
    JWT,

    /**
     * The LocationInner model constructor.
     * @property {module:model/LocationInner}
     */
    LocationInner,

    /**
     * The Registration model constructor.
     * @property {module:model/Registration}
     */
    Registration,

    /**
     * The ValidationError model constructor.
     * @property {module:model/ValidationError}
     */
    ValidationError,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
